World = [
#地图
#"""
#....B...
#.......T
#...BB.B.
#BB..B.BB
#...B....
#..B.....
#.....BB.
#S.....B.
#""",

#地图
"""
........
T.......
........
BB......
........
..B.....
........
S.......
""",

#地图
#"""
#.......T
#........
#........
#........
#........
#........
#........
#S.......
#""",
]

