World = [
#地图1
"""
......T.
........
........
........
........
........
S.......
........
""",

#地图2
"""
......T.
........
........
........
........
........
........
S.......
""",

#地图3
"""
........
T.......
........
BB......
........
..B.....
........
S.......
""",
]

