World = [
#地图1
"""
.T......
........
........
B.......
........
........
........
S.......
""",

#地图2
"""
.......T
........
.....B..
B.......
........
........
........
S.......
""",

#地图3
"""
.......T
........
........
........
........
........
........
S.......
""",
]

